import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="content">

    <div className={styles.container}>

      <Head>
        <title>Adazolhub | Blog Post</title>
        <meta name="description" content="Generated by create next app for adazolhub web development Next JS boilerplate" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image 
          src="/background-01.jpg"
          alt="adazolhub backgound on main"
          layout="intrinsic"
          width={8000}
          height={2939}
          priority
          className={styles.test_image}

        />
        <br />
        <h1  className={styles.title}>
          Welcome to ADAZOL<a href="https://adazolhub.online">HUB!</a>
        </h1 >
        <br />
        <h2>Currently on development mode</h2>
      </main>


    </div>
          
    </div>
  )
}
